#!/usr/bin/env python3
from itertools import product
import string, sys

def generate_characters():
      characters = [char for char in string.printable.replace("\t\n\r\x0b\x0c","")]
      return characters

if __name__ == '__main__':
      try:
            min_characters = int(sys.argv[1])
            max_characters = int(sys.argv[2]) + 1
            output_file = sys.argv[3]
      except:
            print("Usage: python3 {} <MIN_CHARACTERS> <MAX_CHARACTERS> <OUTPUT FILE>".format(sys.argv[0]))
            exit()

      x=0
      f = open(output_file, "w+")
      characters = "".join(generate_characters())
      print("Characters going to be used: "+characters)
      if max_characters < min_characters:
            print("The max number of characters is smaller than the min number of characters\nUsage: python3 {} <MIN_CHARACTERS> <MAX_CHARACTERS> <OUTPUT FILE>".format(sys.argv[0]))
      try:
            for lenght in range(min_characters, max_characters):
                  for item in product(characters, repeat=lenght):
                        f.write("".join(item)+"\n")
                        x+=1
                        print("\rPaswords generated: {}, current password: {}".format(x, "".join(item)), end="\r")
            print("Wordlist finished, passwords created: "+str(x))
      except KeyboardInterrupt:
            print("\nLol")
            f.close()
f.close()
